export const Categories = [
  "Hematology",
  "Clinical Chemistry",
  "Liver Function",
  "Kidney Function",
  "Thyroid Function",
  "Hormones",
  "Cardiac Markers",
  "Coagulation",
  "Infectious Disease - Hepatitis",
  "Infectious Disease - Viral",
  "Infectious Disease - Bacterial",
  "Infectious Disease - Other",
  "Autoimmune/Immunology",
  "Tumor Markers",
  "Microbiology/Culture",
  "Histopathology/Cytology",
  "Urine Analysis",
  "Special Chemistry/Body Fluids",
  "Drug Monitoring/Toxicology",
  "Vitamins & Minerals",
  "Molecular/PCR Tests",
  "Other/Miscellaneous"
]